- releaseNotes/AzureDevOpsPipelineExtension.md
Add release date for Azure DevOps release notes
> Add release date for Azure DevOps release notes

- docs/FeatureManagement/Clients/AspNetCore/Microsoft.FeatureManagement.AspNetCore.md
- Emphasize that the two feature filters in example are built-in
- Fix IDisabledFeatureHandler to IDisabledFeaturesHandler and typo IFeatureManagmentBuilder to IFeatureManagementBuilder
- Fix IDisabledFeatureHandler to IDisabledFeaturesHandler with correct interface structure
- Continue with use of MyFeatureFlags in examples and point out need to add the tag helper for this to work
- Change random percentage to set percentage
> Miscellaneous documentation fixes/improvements

- docs/FeatureManagement/Clients/AspNetCore/Microsoft.FeatureManagement.AspNetCore.md
> Removed non-existent type from docs.

- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Addressed comment here: https://github.com/Azure/AppConfiguration/pull/87#issuecomment-501069767
> Added release date, and replaced 'telemetry' with 'request-tracing'

- docs/REST/authentication.md
For authentication sample code piece
> Add golang sample code

- releaseNotes/AzureDevOpsPipelineExtension.md
* note: currently working on publish the this new version of VstsTask, will merge the PR once the new version gets published.
* Updated: v1.6.7 has just published.
> Update release notes for VstsTask with latest version

- docs/REST/authentication.md
Add PowerShell authentication sample
> Add PowerShell authentication sample

- README.md
- docs/REST/authentication.md
- docs/REST/keys.md
- docs/REST/kv.md
- docs/REST/labels.md
- docs/REST/locks.md
- docs/REST/revisions.md
- docs/REST/versioning.md
> Added versioning doc.

- releaseNotes/AzureDevOpsPipelineExtension.md
* Add release note for VstsTask 1.6.8
* Fix typos in VstsTask release note
> Add VstsTask release note 1.6.8

- releaseNotes/Microsoft.Featuremanagement.md
Updated feature management release notes.
> Updated feature management release notes.

- examples/DotNetCore/WebDemo/Microsoft.Azure.AppConfiguration.WebDemo/Microsoft.Azure.AppConfiguration.WebDemo.csproj
- examples/DotNetCore/WebDemo/Microsoft.Azure.AppConfiguration.WebDemo/Program.cs
- examples/DotNetCore/WebDemo/Microsoft.Azure.AppConfiguration.WebDemo/Startup.cs
- examples/DotNetCore/WebDemo/Microsoft.Azure.AppConfiguration.WebDemo/appsettings.json
- Updated the app to use ASP.NET Core 3.0
- Updated the app to use v3 of AppConfig provider
> Update the web demo app to use the latest config provider

- docs/REST/kv.md
> Fix the sample in API filtering

- docs/Development/fiddler.md
- docs/Development/postman.md
Fix broken links in development docs.
> Fix broken links in development docs.

- releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md
- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Microsoft.Extensions.Configuration.AzureAppConfiguration v3.0.0-preview-011100001-1152
Microsoft.Azure.AppConfiguration.AspNetCore v3.0.0-preview-011100002-1192
> Update release notes for configuration provider

- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
This pull request updates the release notes for version `3.0.2` of the package `Microsoft.Extensions.Configuration.AzureAppConfiguration`.
> Update release notes for .NET Provider v3.0.2

- releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md
This pull request updates the release notes for version `3.0.2` of the package `Microsoft.Azure.AppConfiguration.AspNetCore`.
> Update release notes for AspNetCore Provider v3.0.2

- releaseNotes/AzureDevOpsPipelineExtension.md
- releaseNotes/AzureDevOpsPushPipelineExtension.md
Updated the AzureAppConfiguration Task and AzureAppConfigurationPushTask release notes.
> Updated release notes

- releaseNotes/SpringCloudAzureAppConfigurationConfig.md
- releaseNotes/SpringCloudAzureFeatureManagement.md
Reverts Azure/AppConfiguration#476
> Revert "Updated Release Notes for Spring"

- releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md
- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Update release notes for `Microsoft.Azure.AppConfiguration.AspNetCore` and `Microsoft.Extensions.Configuration.AzureAppConfiguration` for the v4.2.0 release.
> Update .NET config provider release notes for package 4.2.0 

- examples/DotNetCore/AzureFunction/FunctionApp/FunctionApp.csproj
- examples/DotNetCore/AzureFunction/FunctionApp/ReadQueuedMessage.cs
- examples/DotNetCore/AzureFunction/FunctionApp/ShowMessage.cs
Add a queue-triggered sample function with queue name defined in Azure App Configuration.
> Add a queue triggered sample function

- releaseNotes/Microsoft.Featuremanagement.md
Added release notes for Microsoft.FeatureManagement 3.0.0-preview
> Added release notes for Microsoft.FeatureManagement 3.0.0-preview

- examples/Python/python-django-webapp-sample/README.md
- examples/Python/python-django-webapp-sample/quickstartproject/settings.py
- examples/Python/python-django-webapp-sample/requirements.txt
- examples/Python/python-flask-webapp-sample/app.py
- examples/Python/python-flask-webapp-sample/requirements.txt
Updating to GA version
Fixing keyvault usage
> Python Provider GA Update Samples

- releaseNotes/KubernetesProvider.md
K8s provider 1.0.0-preview3 release note
> K8s provider 1.0.0-preview3 release note

- releaseNotes/KubernetesProvider.md
Kubernetes provider preview4 release notes
> Kubernetes provider preview4 release notes

- releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md
- releaseNotes/MicrosoftAzureAppConfigurationFunctionsWorker.md
- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Also updating the release notes files to be clearer and match the format of other files in this folder.
> Add release notes for 7.1.0-preview

- README.md
Add K8s provider repo to readme
> Add K8s provider repo to readme

- releaseNotes/KubernetesProvider.md
K8s provider release note v1.3.1
> K8s provider release note v1.3.1

- releaseNotes/PythonFeatureManagement.md
Removed package section for now as it has yet to be released.
> Python Feature Management Release Notes

- docs/FeatureManagement/Samples/TimeWindowFilter.tests.json
Missing "e". Updated from "happend" to "happened"
> Spell error fix

- .github/workflows/codeql.yml
Fixes https://github.com/Azure/AppConfiguration/actions/runs/12386451194, was failing due to creation not auto detecting the languages in the repo.
> Fix CodeQL

- releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md
- releaseNotes/MicrosoftAzureAppConfigurationFunctionsWorker.md
- releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Also adds AI Configuration request tracing, not mentioned in the notes.
> Add release notes for .NET provider 8.1.2
