releaseNotes/AzureDevOpsPipelineExtension.md
Update Task release note to have v1.6.4
=> Update Task release note to have v1.6.4

docs/REST/authentication.md
Updated authentication docs to use new token separator.
Previously the docs used ',' as a token separator. This is still supported for backward compatibility, however it is not RFC compliant. The docs now use '&' as a token separator in the Authentication header which should be used going forward.
=> Updated authentication docs to use new token separator.

docs/REST/authentication.md
The HMAC is calculated based on RawPath and RawQuery, which results in 401 Unauthorized error for API calls to key or label containing special characters. This change escapes the URL path and query to fix this issue.
Issue reported by user : https://github.com/Azure/AppConfiguration/issues/160
=> Fix authentication issue in Golang sample code

docs/REST/authentication.md
This change reverts the additional encoding for Golang sample code. We need to better understand how encoding is being done in Golang in order to determine the right fix for this case.
=> Revert "Fix authentication issue in Golang sample code (#161)"

README.md, docs/REST/authentication/aad.md, docs/REST/authentication/hmac.md, docs/REST/authentication/index.md, docs/REST/authorization/aad.md, docs/REST/authorization/hmac.md, docs/REST/authorization/index.md, docs/REST/fiddler.md, docs/REST/headers.md, docs/REST/keys.md, docs/REST/kv.md, docs/REST/labels.md, docs/REST/locks.md, docs/REST/postman.md, docs/REST/revisions.md
This PR adds protocol documentation for AAD authentication and authorization. It also establishes a new pattern for documenting authentication vs authorization. This is handled by having a separate authentication and authorization folder. Authentication links have been updated to point to either the authentication index page or the relevant authentication scheme page.
The content of this doc set has already been reviewed internally, but feel free to give another go at reviewing the content.
=> Added authentication and authorization docs for AAD.

releaseNotes/Microsoft.Featuremanagement.md
A user reported experiencing an issue when migrating to 2.0 of the Microsoft.FeatureManagement library. This was due to a new caching strategy added in the library on the latest release. It is worth mentioning this optimization and its side effects in the release notes.
=> Enhanced feature management release notes for 2.0 to mention cache changes and side effects.

releaseNotes/AzureDevOpsPipelineExtension.md
* The latest release removed the deployment of `pipeline-task-lib` to bypass misencoded symbol issue.
=> Add release note for vstsTask 3.0.13

releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md, releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
This pull request adds the release notes for the .NET Configuration Provider v4.0.0-preview.
https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/4.0.0-preview
https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/4.0.0-preview
=> Add release notes for configuration provider v4.0.0-preview

examples/DotNetCore/AzureFunction/FunctionApp/FunctionApp.csproj, examples/DotNetCore/AzureFunction/FunctionApp/Settings.cs, examples/DotNetCore/AzureFunction/FunctionApp/ShowBetaFeature.cs, examples/DotNetCore/AzureFunction/FunctionApp/ShowMessage.cs, examples/DotNetCore/AzureFunction/FunctionApp/Startup.cs
- By taking advantage of the Azure Functions `IFunctionsConfigurationBuilder`, the AppConfig provider can now be added as an additional config source. The Azure Functions existing providers will be preserved. 
- Removed the use of strong type `Settings` and `IOptionsSnapshot` for simplicity. Technically, it's not an AppConfig specific usage pattern. Now that the AppConfig is just one of the providers, users can always do it if it's desired.
- Used the latest API in the config provider v4.1.0 to obtain the refresher instance from the DI
- Updated all dependencies to the latest version
=> Update the Azure Functions example to use AppConfig as a config source

releaseNotes/AzureDevOpsPipelineExtension.md, releaseNotes/AzureDevOpsPushPipelineExtension.md
I've updated the release notes for "releaseNotes/AzureDevOpsPipelineExtension.md" and "https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPushPipelineExtension.md"
=> updated release notes

releaseNotes/Microsoft.Featuremanagement.md
Updated to match the [release page](https://github.com/microsoft/FeatureManagement-Dotnet/releases) of the feature management repo.
=> Added feature management release notes for 2.3 & 2.4

.gitignore, .vscode/settings.json, docs/KVSet/KVSet.v1.0.0.schema.json, docs/KVSet/README.md
With Azure CLI version `2.30.0`, users can import and export the key-value pairs using the `appconfig/kvset` profile.
This PR adds JSON Schema to validate the JSON file using `appconfig/kvset` profile and points examples to using Azure CLI to import and export.
=> Add JSON Schema for `appconfig/kvset` profile

examples/ConfigurationStoreBackup/ConfigurationStoreBackup.csproj, examples/ConfigurationStoreBackup/KeyLabel.cs
This addresses an issue with the sample code from this scenario:
https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-backup-config-store
Fixed an issue where the KeyLabel Equals override was not working with the current behaviour in Azure. When an app config key was being updated (with or without a Label), it was never matched against the keys found in the app config store. 
Also upgraded to .NET 6 and changed the NuGet package references to work with Azure Functions runtime v4.
Deployed updated code to Azure portal and it resolved the issue. Tested with the following scenarios:
- Added a new key to the primary store and the key was synchronized over to the secondary store (added).
- Updated existing key in the primary store and the key was synchronized over to the …
=> ConfigurationStoreBackup sample - Upgraded to .NET 6 and fixed the KeyLabel comparer issue

examples/DotNetFramework/WebFormApp/WebFormApp/Global.asax.cs, examples/DotNetFramework/WebFormApp/WebFormApp/Web.config, examples/DotNetFramework/WebFormApp/WebFormApp/WebFormApp.csproj, examples/DotNetFramework/WebFormApp/WebFormApp/packages.config
Most changes are made automatically by selecting "update all" in the NuGet manager. 
This updated the sample to use v6.0.1 of the provider package and verified that it fixed the refresh bug.
=> Update the WebFormApp to use latest packages

docs/FeatureManagement/FeatureFlag.v1.0.0.schema.json, docs/FeatureManagement/readme.md
Schema link in readme is broken, pointing to v1.0.0 which has been deleted. We probably should keep schema of old version for reference when we publish new version. 
This PR restore the old v1.0.0 schema file, and update the link pointing to the latest (v1.1.0) one.
=> update link and keep old version schema

releaseNotes/AzureDevOpsPipelineExtension.md, releaseNotes/AzureDevOpsPushPipelineExtension.md
This PR updates the AzureDevOpsPushPipelineExtenstion.md and documents importing feature flag breaking change 
GitHub issue #760
=> Updated to document breaking changes

releaseNotes/AzureDevOpsPushPipelineExtension.md
Include the depth property  in example of breaking change when importing configurations with JSON content types
=> Include depth in example of breaking change importing configurations with JSON content types

releaseNotes/AzureDevOpsPipelineExtension.md, releaseNotes/AzureDevOpsPushPipelineExtension.md
This PR updates the release notes for the pipeline task. In the pull task 7.0.0 we have a breaking change that fails when it encounters a multiline secret and the push task we have added support to append prefix to feature flags.
=> Update pipeline task release notes v7.0.0 and v6.4.0

docs/FeatureManagement/FeatureManagement.v1.0.0.schema.json
https://json-schema.org/understanding-json-schema/structuring#dollarref
AFAIU, `$ref` should points to another JSON schema instead of a GH page. 
And it also breaks some schema validation tools, which download related schemas from `$ref` to perform the validation.
=> Update $ref in FeatureManagement schema json

docs/FeatureManagement/FeatureFlag.v1.1.0.schema.json, docs/FeatureManagement/FeatureFlag.v2.0.0.schema.json
"The filter is enabled" sounds like the filter is working/being evaluated. The emphasis here is the result of filter evaluation.
https://github.com/microsoft/FeatureManagement-JavaScript/pull/1#discussion_r1517061416
=> Update description of "requirement_type“ for feature flag schemas

releaseNotes/Microsoft.Featuremanagement.AspNetCore.md, releaseNotes/Microsoft.Featuremanagement.Telemetry.ApplicationInsights.AspNetCore.md, releaseNotes/Microsoft.Featuremanagement.Telemetry.ApplicationInsights.md, releaseNotes/Microsoft.Featuremanagement.md
Fixes misspelling and updates a bullet of the release notes.
=> FeatureManagement 4.0.0-preview2 release notes update

docs/FeatureManagement/FeatureFlag.v2.0.0.schema.json
Before stablizing variant feature flag, we want to drop `configuration_reference` because it doesn't work well with language like python and JS.
=> Remove configuration reference from variant feature flag

examples/QuickStart/JavaScript/QuickStartApp/package.json
With package.json, user can run `npm install` to install the dependencies of the quickstart project.
=> Add package.json for javascript example

releaseNotes/KubernetesProvider.md
draft release notes for v2.1.0
=> Release notes of k8s provider v2.1.0

releaseNotes/MicrosoftAzureAppConfigurationAspNetCore.md, releaseNotes/MicrosoftAzureAppConfigurationFunctionsWorker.md, releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
Include release notes for version 8.2.0-preview, highlighting enhancements and updates to the `Microsoft.Extensions.Configuration.AzureAppConfiguration` reference.
=> Add release notes for version 8.2.0-preview

examples/DotNetCore/ChatApp/ChatApp.sln, examples/DotNetCore/ChatApp/ChatApp/ChatApp.csproj, examples/DotNetCore/ChatApp/ChatApp/Message.cs, examples/DotNetCore/ChatApp/ChatApp/ModelConfiguration.cs, examples/DotNetCore/ChatApp/ChatApp/Program.cs, examples/README.md
Example output of the ChatApp:
=> Add a .NET ChatApp example for AI configuration

examples/DotNetCore/ConsoleApplication/ConsoleApplication.csproj, examples/DotNetCore/ConsoleApplication/Program.cs, examples/DotNetCore/ConsoleApplication/appsettings.json
1.	Upgrade from .NET Core 3.1 to .NET 8
2.	Use the minimal project template style
3.	Switch to DefaultAzureCredential for authentication with Azure App Configuration
GitHub Copilot agent did most of the work :)
=> Upgrade the .NET console app sample to .NET 8

releaseNotes/KubernetesProvider.md
K8s provider v2.3 release note
=> K8s provider v2.3 release note
